import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import AdmZip from 'adm-zip';

const { version } = JSON.parse(
    await readFile(new URL('./package.json', import.meta.url), 'utf8'),
);
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const srcDir = path.join(__dirname, 'src');
const distDir = path.join(__dirname, 'dist');

await rm(distDir, { recursive: true, force: true });
await mkdir(distDir, { recursive: true });
await mkdir(path.join(distDir, 'js'), { recursive: true });

await Promise.all([
    cp(path.join(srcDir, 'css'), path.join(distDir, 'css'), { recursive: true }),
    cp(path.join(srcDir, 'data'), path.join(distDir, 'data'), { recursive: true }),
    cp(path.join(srcDir, 'js'), path.join(distDir, 'js'), { recursive: true }),
    cp(path.join(srcDir, 'index.html'), path.join(distDir, 'index.html')),
    cp(path.join(srcDir, 'cka-tracker.html'), path.join(distDir, 'cka-tracker.html')),
    cp(path.join(srcDir, 'cka-practice-tasks.html'), path.join(distDir, 'cka-practice-tasks.html')),
    cp(path.join(srcDir, '404.html'), path.join(distDir, '404.html')),
    cp(path.join(srcDir, 'robots.txt'), path.join(distDir, 'robots.txt')),
    cp(path.join(srcDir, 'favicon.svg'), path.join(distDir, 'favicon.svg')),
]);

await build({
    entryPoints: [path.join(srcDir, 'js', 'tracker.js')],
    bundle: true,
    format: 'iife',
    loader: {
        '.js': 'jsx',
    },
    jsx: 'automatic',
    legalComments: 'none',
    minify: true,
    outfile: path.join(distDir, 'js', 'tracker.js'),
    platform: 'browser',
    target: ['es2020'],
});

await writeFile(path.join(distDir, '.nojekyll'), '');

// Publish the practice-cluster toolkit so website-only users can fetch it
// without cloning: the individual files (for direct browsing), a self-contained
// bootstrap per platform (get.sh / get.ps1, generated below), and a zip.
const clusterSrcDir = path.join(__dirname, 'cluster');
const clusterDistDir = path.join(distDir, 'cluster');
await mkdir(clusterDistDir, { recursive: true });

const sharedClusterFiles = ['kind-config.yaml', 'README.md'];
const unixClusterFiles = ['lib.sh', 'setup.sh', 'teardown.sh', 'reset.sh'];
const windowsClusterFiles = ['lib.ps1', 'setup.ps1', 'teardown.ps1', 'reset.ps1'];
const publishedClusterFiles = [...sharedClusterFiles, ...unixClusterFiles, ...windowsClusterFiles];

await Promise.all(
    publishedClusterFiles.map((file) =>
        cp(path.join(clusterSrcDir, file), path.join(clusterDistDir, file)),
    ),
);

// Generate the self-contained bootstrap scripts. They EMBED every toolkit file
// and write it to disk, so a piped `curl … | bash` / `irm … | iex` needs no
// further downloads and never has to know its own URL.
const HEREDOC_DELIM = '__CKA_FILE_EOF__';

async function generateUnixBootstrap(files) {
    const blocks = [];
    for (const file of files) {
        const content = await readFile(path.join(clusterSrcDir, file), 'utf8');
        if (content.split('\n').some((line) => line === HEREDOC_DELIM)) {
            throw new Error(`cluster/${file} contains the heredoc delimiter; cannot embed`);
        }
        // content already ends with a newline, so the delimiter lands on its own line.
        blocks.push(`write_file ${JSON.stringify(file)} <<'${HEREDOC_DELIM}'\n${content}${HEREDOC_DELIM}\n`);
    }
    return [
        '#!/usr/bin/env bash',
        '# Self-contained bootstrap for the CKA practice-cluster toolkit.',
        '# GENERATED by build.mjs — do not edit. Embeds the whole toolkit, so it',
        '# needs no network access beyond fetching this one script.',
        '#',
        '#   curl -fsSL <this-site>/cluster/get.sh | bash',
        '#',
        '# Override the target folder with CKA_CLUSTER_DIR.',
        'set -euo pipefail',
        '',
        'DEST="${CKA_CLUSTER_DIR:-cka-practice-cluster}"',
        'echo "Writing CKA practice-cluster toolkit -> ${DEST}/"',
        'mkdir -p "$DEST"',
        '',
        'write_file() {',
        '\tcat > "${DEST}/$1"',
        '\techo "  + $1"',
        '}',
        '',
        blocks.join('\n'),
        'chmod +x "${DEST}"/*.sh',
        '',
        'cat <<EOF',
        '',
        'Done. To create your 2-node practice cluster:',
        '',
        '  cd ${DEST}',
        '  ./setup.sh',
        '',
        'Docker must be installed and running first. kind and kubectl are installed',
        'automatically if missing. See README.md in that folder for details.',
        'EOF',
        '',
    ].join('\n');
}

async function generateWindowsBootstrap(files) {
    const blocks = [];
    for (const file of files) {
        const content = await readFile(path.join(clusterSrcDir, file), 'utf8');
        const body = content.replace(/\n$/, ''); // here-string drops the trailing newline; re-added on write
        if (body.split('\n').some((line) => line.startsWith("'@"))) {
            throw new Error(`cluster/${file} contains a here-string terminator; cannot embed`);
        }
        blocks.push(`Write-CkaFile '${file}' @'\n${body}\n'@\n`);
    }
    return [
        '# Self-contained bootstrap for the CKA practice-cluster toolkit.',
        '# GENERATED by build.mjs — do not edit. Embeds the whole toolkit, so it',
        '# needs no network access beyond fetching this one script.',
        '#',
        '#   irm <this-site>/cluster/get.ps1 | iex',
        '#',
        '# Override the target folder with CKA_CLUSTER_DIR.',
        "$ErrorActionPreference = 'Stop'",
        "$dest = if ($env:CKA_CLUSTER_DIR) { $env:CKA_CLUSTER_DIR } else { 'cka-practice-cluster' }",
        'Write-Host "Writing CKA practice-cluster toolkit -> $dest\\"',
        'New-Item -ItemType Directory -Force -Path $dest | Out-Null',
        '',
        'function Write-CkaFile($name, $content) {',
        '\t[System.IO.File]::WriteAllText((Join-Path $dest $name), ($content -replace "`r`n", "`n") + "`n")',
        '\tWrite-Host "  + $name"',
        '}',
        '',
        blocks.join('\n'),
        "Write-Host ''",
        "Write-Host 'Done. To create your 2-node practice cluster:'",
        "Write-Host ''",
        'Write-Host "  cd $dest"',
        "Write-Host '  ./setup.ps1'",
        "Write-Host ''",
        "Write-Host 'Docker Desktop must be installed and running first. kind and kubectl are'",
        "Write-Host 'installed automatically if missing. See README.md in that folder for details.'",
        '',
    ].join('\n');
}

await Promise.all([
    writeFile(
        path.join(clusterDistDir, 'get.sh'),
        await generateUnixBootstrap([...unixClusterFiles, ...sharedClusterFiles]),
        { mode: 0o755 },
    ),
    writeFile(
        path.join(clusterDistDir, 'get.ps1'),
        await generateWindowsBootstrap([...windowsClusterFiles, ...sharedClusterFiles]),
    ),
]);

// Build one zip per platform (shared files + that platform's scripts).
// Shell scripts get the unix executable bit so they run after a plain unzip.
async function writeClusterZip(name, files) {
    const zip = new AdmZip();
    for (const file of files) {
        const content = await readFile(path.join(clusterSrcDir, file));
        // adm-zip expects the plain unix mode; it adds the file-type bits itself.
        const mode = file.endsWith('.sh') ? 0o755 : 0o644;
        zip.addFile(file, content, '', mode);
    }
    await writeFile(path.join(clusterDistDir, name), zip.toBuffer());
}
await Promise.all([
    writeClusterZip('cka-practice-cluster-unix.zip', [...unixClusterFiles, ...sharedClusterFiles]),
    writeClusterZip('cka-practice-cluster-windows.zip', [
        ...windowsClusterFiles,
        ...sharedClusterFiles,
    ]),
]);

// Cache-bust each asset with a hash of its CONTENT, not the app version. The
// version only changes on release, so version-based busting served stale CSS/JS
// whenever an asset changed within the same version. A content hash always
// changes when the file does, and never when it doesn't (keeps caching benefits).
const assetRefPattern = /(href|src)="((css|data|js)\/[^"]+\.(css|js))"/g;
const assetVersions = new Map();
async function assetVersion(relPath) {
    if (!assetVersions.has(relPath)) {
        let v = version; // fallback if the file somehow isn't on disk
        try {
            const buf = await readFile(path.join(distDir, relPath));
            v = createHash('sha1').update(buf).digest('hex').slice(0, 8);
        } catch {
            // keep version fallback
        }
        assetVersions.set(relPath, v);
    }
    return assetVersions.get(relPath);
}

const htmlPages = ['index.html', 'cka-tracker.html', 'cka-practice-tasks.html'];
await Promise.all(
    htmlPages.map(async (file) => {
        const filePath = path.join(distDir, file);
        let content = await readFile(filePath, 'utf8');
        content = content.replaceAll('__APP_VERSION__', `v${version}`);
        // Pre-resolve every referenced asset's hash, then rewrite synchronously.
        const refs = [...new Set([...content.matchAll(assetRefPattern)].map((m) => m[2]))];
        await Promise.all(refs.map((p) => assetVersion(p)));
        content = content.replace(
            assetRefPattern,
            (_full, attr, relPath) => `${attr}="${relPath}?v=${assetVersions.get(relPath)}"`,
        );
        await writeFile(filePath, content);
    }),
);